name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/base.txt ]; then pip install -r requirements/base.txt; fi
        if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
    
    - name: Build and package application
      run: |
        python setup.py sdist bdist_wheel
    
    - name: Set up configuration for development
      run: |
        cp config/development/* config/default/
    
    - name: Deploy to development server
      run: |
        # This is where you would deploy your application to your development server
        # Example using SSH to deploy to a server
        # Install SSH key
        echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 deploy_key
        
        # Deploy using rsync over SSH
        rsync -avz --delete -e "ssh -i deploy_key -o StrictHostKeyChecking=no" dist/ ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }}:${{ secrets.DEV_APP_PATH }}
        
        # Run deployment script on remote server
        ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} "cd ${{ secrets.DEV_APP_PATH }} && ./deployment/scripts/deploy.sh"
        
        # Clean up
        rm deploy_key
    
    - name: Run post-deployment health checks
      run: |
        # Wait a bit for the service to start
        sleep 30
        # Check if the service is running properly
        curl -sSf ${{ secrets.DEV_HEALTH_CHECK_URL }} || exit 1
    
    - name: Send deployment notification
      if: always()
      run: |
        # Send notification about the deployment status
        # This could be an email, Slack message, etc.
        echo "Deployment to development environment completed with status: ${{ job.status }}"